### ISSUE TITLE
Errod discord.js version 12

### ISSUE THREAD

**Issue by LeMalCestBien** [packcord/discord-backup#3]
Hello i have a problem...

I type: b!create and i have this error:

`Uncaught Promise Error You must install and use discord.js version 12 or higher to use this package!
[FATAL] Possibly Unhandled Rejection at: Promise Promise {
'You must install and use discord.js version 12 or higher to use this package!' } reason: undefined`

How to resolve this??

**Comment by DiscordSecure** [comment]
:-(

**Comment by Androz2091** [comment]
Upgrade your discord js version with `npm i discordjs/discord.js`

**Comment by DiscordSecure** [comment]
we already try but it does not work

**Comment by LeMalCestBien** [comment]
But the release is 11.5.1...

**Comment by Androz2091** [comment]
Yes, you need to use the dev branch (some features are not available in the last release).

**Comment by LeMalCestBien** [comment]
How to switch from the stable branch to the dev branch?

**Comment by LeMalCestBien** [comment]
How to switch from the stable branch to the dev branch?

**Comment by LeMalCestBien** [comment]
Problem solved thanks you just had to be patient for the installation
