### ISSUE TITLE
Error installing discord-backup

### ISSUE THREAD

**Issue by Stroketon** [packcord/discord-backup#4]
https://stroketon.net/uploads/6bya9yu8.png

**Comment by Androz2091** [comment]
* install git
* open git bash
* retry to install the package

**Comment by MackenzieMolloy** [comment]
![image](https://user-images.githubusercontent.com/48184419/76109246-fae0dc00-5fd3-11ea-92e5-ce6e373c8008.png)
I get this error installing the package, (v11). Any ideas? I've done that stuff above

**Comment by Androz2091** [comment]
Yes, Discord.js released v12.0.1, and v11 is now outdated.

**Comment by MackenzieMolloy** [comment]
> Yes, Discord.js released v12.0.1, and v11 is now outdated.

Im trying to install the version of discord-backup that suppots v11 but it didnt work as you can see in the picture

**Comment by MackenzieMolloy** [comment]
@Androz2091 Do you have discord? It would be easier as it saves me reloading this page every so often.
