### ISSUE TITLE
DiscordJS ver 12

### ISSUE THREAD

**Issue by DarkWise555** [packcord/discord-backup#5]
This isn't even a thing yet?..
How is one supposed to go about getting version 12 of it xD

**Comment by Androz2091** [comment]
Some useful links 😉 

To install version 12: `npm i discordjs/discord.js`
To migrate v11 code to v12: https://github.com/discordjs/guide/blob/v12-changes/guide/additional-info/changes-in-v12.md

**Comment by Androz2091** [comment]
If you have any other questions go to the official discordjs server
